apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vmonitor-metric-agent.kubestateconfig" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vmonitor-metric-agent.labels" . | nindent 4 }}
data:
  telegraf.conf: |+
    {{- $tplVersion := include "detect.version" . }}
    {{ template "global_tags" .Values.configKubeState.global_tags }}
    {{ template "agent" .Values.configKubeState.agent }}
    {{ template "processors" (list $tplVersion .Values.configKubeState.processors) }}
    {{ template "aggregators" (list $tplVersion .Values.configKubeState.aggregators) }}
    {{ template "outputs" (list $tplVersion .Values.configKubeState.outputs) }}
    [[outputs.vngcloud_vmonitor]]
      url = "https://${VMONITOR_SITE}:443"
      insecure_skip_verify = false
      data_format = "vngcloud_vmonitor"
      client_id = "${IAM_CLIENT_ID}"
      client_secret = "${IAM_CLIENT_SECRET}"
      iam_url = "${IAM_URL}"
      timeout = "30s"
    {{ template "inputs" (list $tplVersion .Values.configKubeState.inputs) }}
    {{ template "monitor_self" .Values.configKubeState.monitor_self }}

