apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vmonitor-metric-agent.secretconfigname" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vmonitor-metric-agent.labels" . | nindent 4 }}
type: Opaque
data:
  CLUSTER_NAME: {{ default "cluter-k8s" .Values.vmonitor.clusterName | b64enc | quote }}
  API_KEY: {{ default "missing" .Values.vmonitor.apiKey | b64enc | quote }}
  VMONITOR_SITE: {{ default "monitoring-agent.vngcloud.vn" .Values.vmonitor.vmonitorSite | b64enc | quote }}
